"""memories table

Autogenerated from sibyl.models.memory, then given a readable revision id to
match 0001 — a sequence anyone can order by eye beats a hash.

Revision ID: 0002_memories
Revises: 0001_jobs
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0002_memories"
down_revision: str | None = "0001_jobs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # job_id unique so re-indexing a job replaces its memory instead of adding a
    # duplicate; embedding_model indexed because every query filters on it, to
    # keep two incompatible vector spaces from being compared.
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memories_job_id"), ["job_id"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_memories_embedding_model"), ["embedding_model"], unique=False
        )


def downgrade() -> None:
    with op.batch_alter_table("memories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memories_embedding_model"))
        batch_op.drop_index(batch_op.f("ix_memories_job_id"))
    op.drop_table("memories")
